//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// WaveEndPoint.rc で使用
//
#define IDC_BTNCLEAR                    5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_BTN_STOP                    105
#define IDC_BTN_AUTORCPCHK              106
#define IDC_BTN_AUTORCPSTOP             107
#define IDR_MAINFRAME                   128
#define IDR_WaveEndPointTYPE            130
#define IDB_CONFIG_A                    310
#define IDB_CONFIG_D                    311
#define IDB_CONFIG_P                    312
#define IDB_EXIT_A                      313
#define IDB_EXIT_D                      314
#define IDB_EXIT_P                      315
#define IDB_LOG_A                       316
#define IDB_LOG_D                       317
#define IDB_LOG_P                       318
#define IDB_MAIN_A                      319
#define IDB_MAIN_D                      320
#define IDB_MAIN_P                      321
#define IDB_RECIPE_A                    322
#define IDB_RECIPE_D                    323
#define IDB_RECIPE_P                    324
#define IDB_WAVE_A                      325
#define IDB_WAVE_D                      326
#define IDB_WAVE_P                      327
#define IDB_YAC                         328
#define IDD_HEAD                        329
#define IDD_ROWWAVEMON                  331
#define IDB_SMALL_PC1                   333
#define IDB_SMALL_PC2                   334
#define IDB_SMALL_PC3                   335
#define IDB_SMALL_PC4                   336
#define IDB_SMALL_PC5                   337
#define IDD_CONFIG                      338
#define IDB_CFG_TREE                    340
#define IDD_EQCONFIG                    341
#define IDD_NUMEDIT                     343
#define IDD_ENUMEDIT                    353
#define IDD_STRINGEDIT                  355
#define IDD_WAVECONFIG                  357
#define IDD_PLCCONFIG                   359
#define IDD_COMMANDPAGE                 361
#define IDD_PCMONITOR                   363
#define IDD_MANUAL_LOGSAVE              365
#define IDB_ANALYSIS_A                  367
#define IDB_ANALYSIS_D                  368
#define IDB_ANALYSIS_P                  369
#define IDD_ANALYSIS                    370
#define IDD_SIMULATION                  372
#define IDB_SIMULATION_ACT              374
#define IDB_GREEN_CIRCLE                375
#define IDB_GREEN_CIRCLE2               376
#define IDB_GRAY_CIRCLE                 377
#define IDB_PINK_CIRCLE                 378
#define IDB_RED_CIRCLE                  379
#define IDB_BITMAP6                     380
#define IDB_YELLOW_CIRCLE               380
#define IDD_SENSORCFG                   381
#define IDD_RCPEDIT                     384
#define IDB_FILE                        386
#define IDD_WAVECFG_LIST                387
#define IDD_RCPCOPY                     389
#define IDD_MAIN_PC                     391
#define IDD_CHGEPDMODE                  393
#define IDD_RCPSELECT                   395
#define IDD_EPDLOG                      397
#define IDD_RCP_STEPVIEW                399
#define IDD_RECIPE_CHK                  400
#define IDB_RCPCHK_ACT                  401
#define IDD_PC_SELECT                   402
#define IDD_CHKRCPEDIT                  403
#define IDD_CHKRCPWAVECFG               404
#define IDD_WAVEREFERENCE               405
#define IDD_ALARM                       407
#define IDB_ALMLEVEL                    409
#define IDB_ALARM_ACT                   410
#define IDB_ALARM_FOCUS                 411
#define IDB_ALARM_DISABLE               412
#define IDB_ALARM_PUSH                  413
#define IDD_ALARMLOG                    414
#define IDI_ICON1                       416
#define IDI_ICON_PC1                    416
#define IDI_ICON_PC2                    417
#define IDB_PASSWORD_FOCUS              417
#define IDI_ICON_PC3                    418
#define IDB_PASSWORD_PUSH               418
#define IDI_ICON_PC4                    419
#define IDD_PASSWORD                    419
#define IDI_ICON_PC5                    420
#define IDD_USERLIST                    421
#define IDB_ENABLE                      423
#define IDD_SENSORCFG_USB               424
#define IDD_AUTO_RCPCHECK               427
#define IDB_ASCEND                      429
#define IDB_DESCEND                     430
#define IDB_FLAT                        431
#define IDB_PEAK                        432
#define IDC_DRAW_RECT                   1000
#define IDC_ED_LEVEL1                   1001
#define IDC_USERID                      1001
#define IDC_ED_LEVEL2                   1002
#define IDC_PASSWORD                    1002
#define IDC_ED_LEVEL3                   1003
#define IDC_ED_LEVEL4                   1004
#define IDB_CMD_BTN1                    1004
#define IDC_BMP_PC                      1005
#define IDB_CMD_BTN2                    1005
#define IDC_RECT_TIME                   1006
#define IDB_CMD_BTN3                    1006
#define IDC_TREE_CFG                    1007
#define IDB_CMD_BTN4                    1007
#define IDC_ED_PC1                      1008
#define IDB_CMD_BTN5                    1008
#define IDC_ED_PC2                      1009
#define IDB_CMD_BTN6                    1009
#define IDC_ED_PC3                      1010
#define IDB_CMD_BTN7                    1010
#define IDC_ED_PC4                      1011
#define IDB_CMD_BTN8                    1011
#define IDC_ED_PC5                      1012
#define IDB_CMD_BTN9                    1012
#define IDC_ED_PRESSUNIT                1013
#define IDB_CMD_BTN10                   1013
#define IDC_ED_LOGCYCLE                 1013
#define IDC_ED_WAVECNT                  1014
#define IDB_CMD_BTN11                   1014
#define IDC_ED_NO1                      1015
#define IDC_ED_WAVECNT2                 1015
#define IDC_ED_DRIVERTYPE               1015
#define IDC_ED_NO2                      1016
#define IDC_ED_NO3                      1017
#define IDC_ED_NO4                      1018
#define IDC_CMB_WAVE1                   1018
#define IDC_ED_NO5                      1019
#define IDC_CMB_WAVE2                   1019
#define IDC_CMB_DIFF_BASEWAVE1          1019
#define IDC_ED_NO6                      1020
#define IDC_CMB_WAVE3                   1020
#define IDC_CMB_DIFF_ADDWAVE1           1020
#define IDC_ED_NO7                      1021
#define IDC_CMB_WAVE4                   1021
#define IDC_CMB_DIFF_BASEWAVE2          1021
#define IDC_ED_NO8                      1022
#define IDC_CMB_WAVE5                   1022
#define IDC_CMB_DIFF_ADDWAVE2           1022
#define IDC_ED_NO9                      1023
#define IDC_CMB_WAVE6                   1023
#define IDC_ED_NO10                     1024
#define IDC_CMB_WAVE7                   1024
#define IDC_ED_NO11                     1025
#define IDC_CMB_WAVE8                   1025
#define IDC_ED_NO12                     1026
#define IDC_CMB_WAVE9                   1026
#define IDC_ED_NO13                     1027
#define IDC_CMB_WAVE10                  1027
#define IDC_ED_NO14                     1028
#define IDC_RECT_GRAPH                  1028
#define IDC_ED_NO15                     1029
#define IDC_ED_NO16                     1030
#define IDC_ED_Y_MAX                    1030
#define IDC_ED_NO17                     1031
#define IDC_ED_SAMPLINGTIME             1031
#define IDC_ED_DATA1                    1031
#define IDC_ED_NO18                     1032
#define IDC_ED_MAXTIME                  1032
#define IDC_BTN_SAVE                    1032
#define IDC_ED_DATA2                    1032
#define IDC_ED_NO19                     1033
#define IDC_BTN_NEW                     1033
#define IDC_ED_DATA3                    1033
#define IDC_ED_NO20                     1034
#define IDC_TREE_FILE                   1034
#define IDC_BTN_EDIT                    1034
#define IDC_ED_DATA4                    1034
#define IDC_ED_NO21                     1035
#define IDC_ED_PC                       1035
#define IDC_BTN_REMOVE                  1035
#define IDC_ED_DATA5                    1035
#define IDC_ED_NO22                     1036
#define IDC_ED_SAMPLETIME               1036
#define IDC_BTN_COPY                    1036
#define IDC_ED_ENDSTATUS                1036
#define IDC_ED_NO23                     1037
#define IDC_ED_FILENAME                 1037
#define IDC_ED_NO24                     1038
#define IDC_WAVELENGTH_RECT             1038
#define IDC_ED_NO25                     1039
#define IDC_ED_Y_MIN                    1039
#define IDC_SCROLLBAR1                  1039
#define IDC_ED_NO26                     1040
#define IDC_ED_X_MAX                    1040
#define IDC_ED_ENDTIME                  1040
#define IDC_ED_NO27                     1041
#define IDC_ED_CURRTIME                 1041
#define IDC_ED_NO28                     1042
#define IDC_ED_SERCHSTART               1042
#define IDC_ED_NO29                     1043
#define IDC_ED_SERCHEND                 1043
#define IDC_ED_NO30                     1044
#define IDC_ED_WaveLen1                 1044
#define IDC_ED_NO31                     1045
#define IDC_ED_WaveLen2                 1045
#define IDC_ED_NO32                     1046
#define IDC_ED_WaveLen3                 1046
#define IDC_ED_NO33                     1047
#define IDC_ED_WaveLen4                 1047
#define IDC_ED_NO34                     1048
#define IDC_ED_WaveLen5                 1048
#define IDC_ED_NO35                     1049
#define IDC_ED_WaveLen6                 1049
#define IDC_ED_STARTWAVE                1049
#define IDC_ED_NO36                     1050
#define IDC_ED_WaveLen7                 1050
#define IDC_ED_SERCHEND2                1050
#define IDC_ED_ENDWAVE                  1050
#define IDC_ED_NO37                     1051
#define IDC_ED_WaveLen8                 1051
#define IDC_ED_NO38                     1052
#define IDC_ED_WaveLen9                 1052
#define IDC_ED_NO39                     1053
#define IDC_ED_WaveLen10                1053
#define IDC_ED_NO40                     1054
#define IDC_ED_MAX1                     1054
#define IDC_ED_NO41                     1055
#define IDC_ED_MAX2                     1055
#define IDC_ED_NO42                     1056
#define IDC_ED_MAX3                     1056
#define IDC_ED_NO43                     1057
#define IDC_ED_MAX4                     1057
#define IDC_ED_NO44                     1058
#define IDC_ED_MAX5                     1058
#define IDC_ED_NO45                     1059
#define IDC_ED_MAX6                     1059
#define IDC_ED_NO46                     1060
#define IDC_ED_MAX7                     1060
#define IDC_ED_NO47                     1061
#define IDC_ED_MAX8                     1061
#define IDC_ED_NO48                     1062
#define IDC_ED_MAX9                     1062
#define IDC_ED_NO49                     1063
#define IDC_ED_MAX10                    1063
#define IDC_ED_NO50                     1064
#define IDC_ED_DiffWaveLen1             1064
#define IDC_ED_NO51                     1065
#define IDC_BTN_SERCH                   1065
#define IDC_ED_NO52                     1066
#define IDC_ED_DIFF1                    1066
#define IDC_ED_NO53                     1067
#define IDC_ED_DiffWaveLen2             1067
#define IDC_ED_NO54                     1068
#define IDC_ED_DIFF2                    1068
#define IDC_ED_NO55                     1069
#define IDC_ED_DiffWaveLen3             1069
#define IDC_ED_NO56                     1070
#define IDC_ED_DIFF3                    1070
#define IDC_ED_NO57                     1071
#define IDC_ED_DiffWaveLen4             1071
#define IDC_ED_NO58                     1072
#define IDC_ED_DIFF4                    1072
#define IDC_ED_NO59                     1073
#define IDC_ED_DiffWaveLen5             1073
#define IDC_ED_NO60                     1074
#define IDC_ED_DIFF5                    1074
#define IDC_ED_NO61                     1075
#define IDC_ED_DiffWaveLen6             1075
#define IDC_ED_NO62                     1076
#define IDC_ED_DIFF6                    1076
#define IDC_ED_NO63                     1077
#define IDC_ED_DiffWaveLen7             1077
#define IDC_ED_NO64                     1078
#define IDC_ED_DIFF7                    1078
#define IDC_ED_NO65                     1079
#define IDC_ED_DiffWaveLen8             1079
#define IDC_ED_NO66                     1080
#define IDC_ED_DIFF8                    1080
#define IDC_ED_NO67                     1081
#define IDC_ED_DiffWaveLen9             1081
#define IDC_ED_NO68                     1082
#define IDC_ED_DIFF9                    1082
#define IDC_ED_NO69                     1083
#define IDC_ED_DiffWaveLen10            1083
#define IDC_ED_NO70                     1084
#define IDC_ED_DIFF10                   1084
#define IDC_ED_NO71                     1085
#define IDC_CHK_MAX1                    1085
#define IDC_ED_NO72                     1086
#define IDC_CHK_MAX2                    1086
#define IDC_ED_NO73                     1087
#define IDC_CHK_MAX3                    1087
#define IDC_ED_NO74                     1088
#define IDC_CHK_MAX4                    1088
#define IDC_ED_NO75                     1089
#define IDC_CHK_MAX5                    1089
#define IDC_CHK_MAX6                    1090
#define IDC_CHK_MAX7                    1091
#define IDC_CHK_MAX8                    1092
#define IDC_CHK_MAX9                    1093
#define IDC_CHK_MAX10                   1094
#define IDC_CHK_DIFF1                   1095
#define IDC_CHK_DIFF2                   1096
#define IDC_CHK_DIFF3                   1097
#define IDC_CHK_DIFF4                   1098
#define IDC_CHK_DIFF5                   1099
#define IDC_CHK_DIFF6                   1100
#define IDC_CHK_DIFF7                   1101
#define IDC_CHK_DIFF8                   1102
#define IDC_CHK_DIFF9                   1103
#define IDC_CHK_DIFF10                  1104
#define IDC_ED_GRAPH_START_TM           1105
#define IDC_ED_GRAPH_END_TM             1106
#define IDC_RECT_SELGRAPH               1107
#define IDC_ED_GRAPH_YMAX               1108
#define IDC_ED_AVECNT1                  1109
#define IDC_ED_GRAPH_MAX2               1109
#define IDC_ED_OFFSET1                  1110
#define IDC_ED_GAIN1                    1111
#define IDC_CMB_ADDWAVE1                1112
#define IDC_CMB_SUBSTWAVE1              1113
#define IDC_BTN_GRAPH1                  1114
#define IDC_BTN_LOAD1                   1115
#define IDC_BTN_LOADWAVE                1115
#define IDC_BTN_SAVE1                   1116
#define IDC_ED_SENSOR1                  1116
#define IDC_ED_Y1_5                     1117
#define IDC_ED_SENSOR2                  1117
#define IDC_ED_Y1_4                     1118
#define IDC_ED_SENSOR3                  1118
#define IDC_ED_Y1_3                     1119
#define IDC_ED_SENSOR4                  1119
#define IDC_ED_Y1_2                     1120
#define IDC_ED_SENSOR5                  1120
#define IDC_ED_Y1_1                     1121
#define IDC_BMP_SENSOR1                 1121
#define IDC_ED_FILE1                    1122
#define IDC_BMP_SENSOR2                 1122
#define IDC_ED_INTEGRATIONTIME          1122
#define IDC_BMP_SENSOR3                 1123
#define IDC_ED_GAIN                     1123
#define IDC_ED_NO                       1123
#define IDC_BMP_SENSOR4                 1124
#define IDC_ED_TRIGGEREDGE              1124
#define IDC_ED_NAME                     1124
#define IDC_ED_DIFF_0                   1124
#define IDC_BMP_SENSOR5                 1125
#define IDC_ED_TRIGGERMODE              1125
#define IDC_ED_WAVE_A_CNT               1125
#define IDC_BTN_GETPRM                  1126
#define IDC_ED_STATUS1                  1126
#define IDC_BTN_GETMACADDR              1126
#define IDC_ED_WAVE_A_OFFGAIN_VAL1      1126
#define IDC_BTN_SETPRM                  1127
#define IDC_ED_STATUS2                  1127
#define IDC_ED_WAVE_A_OFFGAIN_VAL2      1127
#define IDC_ED_EEPROMLOADDEF            1128
#define IDC_ED_STATUS3                  1128
#define IDC_ED_WAVE_B1_CNT              1128
#define IDC_BTN_SETLOADDEF              1129
#define IDC_ED_STATUS4                  1129
#define IDC_BTN_GETWAVECNT2             1129
#define IDC_ED_WAVE_B1_OFFGAIN_VAL1     1129
#define IDC_ED_UNITID                   1130
#define IDC_ED_STATUS5                  1130
#define IDC_ED_WAVE_B1_OFFGAIN_VAL2     1130
#define IDC_ED_SENSORNAME               1131
#define IDC_BMP_STATUS1                 1131
#define IDC_ED_EPD_IP1                  1131
#define IDC_ED_WAVE_B2_CNT              1131
#define IDC_ED_CALIBRATE_A              1132
#define IDC_BMP_STATUS2                 1132
#define IDC_ED_WAVE_B2_OFFGAIN_VAL1     1132
#define IDC_ED_SERIALNO                 1133
#define IDC_BMP_STATUS3                 1133
#define IDC_ED_EPD_IP2                  1133
#define IDC_ED_WAVE_B2_OFFGAIN_VAL2     1133
#define IDC_ED_UPPER_WAVE               1134
#define IDC_BMP_STATUS4                 1134
#define IDC_ED_WAVE_SEL1                1134
#define IDC_ED_LOWER_WAVE               1135
#define IDC_BMP_STATUS5                 1135
#define IDC_ED_WAVE_SEL2                1135
#define IDC_BTN_READINFO                1136
#define IDC_ED_PLCCOMM                  1136
#define IDC_BTN_READWAVELEN             1136
#define IDC_ED_WAVE_SEL3                1136
#define IDC_BTN_WRITEINFO               1137
#define IDC_BMP_PLC                     1137
#define IDC_ED_OPERAND1                 1137
#define IDC_ED_CALIBRATE_B1             1138
#define IDC_ED_OPERAND2                 1138
#define IDC_ED_CALIBRATE_B2             1139
#define IDC_ED_CALIBRATE_B3             1140
#define IDC_ED_CALIBRATE_B4             1141
#define IDC_ED_CALIBRATE_B5             1142
#define IDC_BTN_READCALIB               1143
#define IDC_BTN_WRITECALIB              1144
#define IDC_ED_EPD_IP3                  1144
#define IDC_ED_COOLCOUNT                1145
#define IDC_ED_EPD_IP4                  1145
#define IDC_ED_STAT_BIT0                1146
#define IDC_BTN_SETIPADDR               1146
#define IDC_ED_STAT_BIT3                1147
#define IDC_ED_STAT_BIT4                1148
#define IDC_BTN_SETINTEGRATION          1148
#define IDC_ED_STAT_BIT5                1149
#define IDC_BTN_GETINTEGRATE            1149
#define IDC_ED_STAT_BIT7                1150
#define IDC_ED_PC_IP1                   1150
#define IDC_BMP_BIT0                    1151
#define IDC_ED_PC_IP2                   1151
#define IDC_BMP_BIT3                    1152
#define IDC_CMB_WAVE1_AVE1              1152
#define IDC_ED_PC_IP3                   1152
#define IDC_BMP_BIT4                    1153
#define IDC_CMB_WAVE1_AVE2              1153
#define IDC_TREE1                       1153
#define IDC_ED_PC_IP4                   1153
#define IDC_BMP_BIT5                    1154
#define IDC_CMB_WAVE1_AVE3              1154
#define IDC_LIST1                       1154
#define IDC_LIST_RECIPE                 1154
#define IDC_LIST_WAVECFG                1154
#define IDC_LIST_FROM                   1154
#define IDC_LIST_RCP                    1154
#define IDC_LIST_WAVE                   1154
#define IDC_LIST_WAVE1                  1154
#define IDC_LIST_ALARM                  1154
#define IDC_LIST_ALM                    1154
#define IDC_BMP_BIT7                    1155
#define IDC_ED_PCNAME                   1155
#define IDC_LIST_TO                     1155
#define IDC_LIST_WAVE2                  1155
#define IDC_ED_STAT_BIT8                1156
#define IDC_ED_DLL_VERSION              1156
#define IDC_ED_RCPNO                    1156
#define IDC_LIST_WAVE3                  1156
#define IDC_ED_RCPNAME                  1157
#define IDC_LIST_WAVE4                  1157
#define IDC_ED_MAC_ADDRESS              1157
#define IDC_ED_COMMENT                  1158
#define IDC_ED_RCPCOMMENT               1158
#define IDC_ED_WAVECFGNO                1158
#define IDC_LIST_WAVE5                  1158
#define IDC_ED_INIT_IPADDR              1158
#define IDC_CMB_WAVE                    1159
#define IDC_ED_STARTLEVEL_SW            1159
#define IDC_ED_INIT_SUBNET              1159
#define IDC_CHK_JUST_LEVEL              1160
#define IDC_ED_JUSTLEVEL_SW             1160
#define IDC_ED_INIT_GATEWAY             1160
#define IDC_CHK_JUST_DIFF               1161
#define IDC_ED_JUSTDIFF_SW              1161
#define IDC_ED_INIT_PORTNO              1161
#define IDC_CHK_JUST_LEVEL3             1162
#define IDC_CHK_END_DIFF                1162
#define IDC_ED_JUSTLIMIT_SW             1162
#define IDC_ED_INIT_VENDER              1162
#define IDC_BTN_1                       1163
#define IDC_CHK_START_LIMIT             1163
#define IDC_ED_ENDLEVEL_SW              1163
#define IDC_ED_INIT_PRODUCT             1163
#define IDC_BTN_2                       1164
#define IDC_CHK_END_LEVEL               1164
#define IDC_ED_ENDDIFF_SW1              1164
#define IDC_ED_INIT_SERIAL              1164
#define IDC_BTN_3                       1165
#define IDC_CHK_JUST_LIMIT              1165
#define IDC_ED_ENDDIFF_SW2              1165
#define IDC_ED_INIT_FIRMWARE            1165
#define IDC_BTN_4                       1166
#define IDC_CHK_END_LIMIT               1166
#define IDC_ED_FLATWAVE_SW              1166
#define IDC_ED_INIT_UNITID              1166
#define IDC_BTN_5                       1167
#define IDC_CHK_JUST_LEVEL5             1167
#define IDC_CHK_OV_TIME                 1167
#define IDC_ED_ENDLIMIT_SW              1167
#define IDC_ED_INIT_SENSORID            1167
#define IDC_BTN_6                       1168
#define IDC_CHK_JUST_LEVEL6             1168
#define IDC_CHK_OV_RATE                 1168
#define IDC_ED_OVETCHTIME_SW            1168
#define IDC_BTN_GETNETINFO              1168
#define IDC_BTN_7                       1169
#define IDC_ED_DEADTIME                 1169
#define IDC_BTN_GETPORTNO               1169
#define IDC_BTN_8                       1170
#define IDC_ED_STARTLEVEL               1170
#define IDC_BTN_GETPRODUCT              1170
#define IDC_BTN_9                       1171
#define IDC_ED_START_LIMIT              1171
#define IDC_ED_OVETCHRATE_SW            1171
#define IDC_BTN_GETPRODUCT2             1171
#define IDC_BTN_GETUNITINFO             1171
#define IDC_BTN_0                       1172
#define IDC_ED_JUSTLEVEL                1172
#define IDC_BTN_COLON                   1173
#define IDC_BTN_ATMARK                  1173
#define IDC_ED_JUST_DIFF                1173
#define IDC_ED_JUSTDIFF                 1173
#define IDC_BTN_DEL                     1174
#define IDC_ED_JUST_LIMIT               1174
#define IDC_ED_JUSTLIMIT                1174
#define IDC_BTN_MINUS                   1175
#define IDC_BTN_PLUS                    1175
#define IDC_ED_ENDLEVEL                 1175
#define IDC_ED_FLD                      1176
#define IDC_ED_END_DIFF                 1176
#define IDC_ED_ENDDIFF1                 1176
#define IDC_ED_END_LIMIT                1177
#define IDC_ED_ENDDIFF2                 1177
#define IDC_LST_ENUMSTR                 1178
#define IDC_BTN_CAPS                    1178
#define IDC_ED_OVER_ETCH_TIME           1178
#define IDC_ED_FLATLEVEL                1178
#define IDC_BTN_SPACE                   1179
#define IDC_ED_OVER_ETCH_RATE           1179
#define IDC_ED_FLATTIME                 1179
#define IDC_BTN_DEL2                    1180
#define IDC_CHK_END_FLAT                1180
#define IDC_ED_ENDLIMIT                 1180
#define IDC_ED_END_FLAT                 1181
#define IDC_ED_OVERETCHTIME             1181
#define IDC_ED_END_LIMIT2               1182
#define IDC_ED_END_FLAT_TIME            1182
#define IDC_ED_OVERETCHRATE             1182
#define IDC_ED_STEPCOMMENT              1183
#define IDC_ED_WAVE1                    1183
#define IDC_LIST_STEP                   1184
#define IDC_ED_WAVE2                    1184
#define IDC_BTN_ADD_STEP                1185
#define IDC_ED_WAVE3                    1185
#define IDC_BTN_DEL_STEP                1186
#define IDC_ED_WAVE4                    1186
#define IDC_BTN_INSERT_STEP             1187
#define IDC_ED_ADD_WAVE                 1187
#define IDC_BTN_COPY_STEP               1188
#define IDC_ED_SUB_WAVE                 1188
#define IDC_CHK_END_DIFF2               1189
#define IDC_ED_MOVEAVECNT               1189
#define IDC_ED_END_DIFF2                1190
#define IDC_ED_OFFSET                   1190
#define IDC_RDO_START_OVER              1191
#define IDC_ED_WAVECFGNAME              1191
#define IDC_RDO_START_UNDER             1192
#define IDC_RDO_JUST_OVER               1193
#define IDC_RDO_JUST_UNDER              1194
#define IDC_RDO_END_OVER                1195
#define IDC_ED_FROM_NO                  1195
#define IDC_RDO_END_UNDER               1196
#define IDC_ED_FROM_NAME                1196
#define IDC_CHK_JUST_LEVEL2             1197
#define IDC_CHK_START_LEVEL             1197
#define IDC_ED_TO_NO                    1197
#define IDC_ED_DEADTIME2                1198
#define IDC_ED_STEP                     1198
#define IDC_ED_TO_NAME                  1198
#define IDC_CMB_FROM                    1199
#define IDC_CHK_JUST_PEAK               1199
#define IDC_CMB_TO                      1200
#define IDC_ED_RECIPE                   1200
#define IDC_RDO_JUST_PEAK_HIGH          1200
#define IDC_BTN_RCP                     1201
#define IDC_RDO_JUST_PEAK_LOW           1201
#define IDC_ED_WAVECFG                  1202
#define IDC_ED_JUSTPEAKVAL              1202
#define IDC_ED_JUSTPEAKCHGVAL           1202
#define IDC_ED_RAWDATA                  1203
#define IDC_ED_AUTO_GAIN                1203
#define IDC_ED_CALCDATA                 1204
#define IDC_CHK_AUTO_GAIN               1204
#define IDC_ED_TIME_MID                 1205
#define IDC_CHK_JUST_BOX                1205
#define IDC_ED_CALCDATA2                1205
#define IDC_ED_DIFFDATA                 1205
#define IDC_ED_TIME_MAX                 1206
#define IDC_RDO_JUST_BOX_ASC            1206
#define IDC_BTN_START                   1207
#define IDC_RDO_JUST_BOX_DES            1207
#define IDC_BMP_START                   1208
#define IDC_RDO_JUST_BOX_FLAT           1208
#define IDC_ED_DEADTIME_SET             1209
#define IDC_BTN_MODE                    1209
#define IDC_ED_JUST_BOX_LEVEL           1209
#define IDC_ED_TOTALTIME                1210
#define IDC_ED_MODE                     1210
#define IDC_ED_JUST_BOX_TIME            1210
#define IDC_ED_DEADTIME_MON             1211
#define IDC_BTN_REMOTE                  1211
#define IDC_ED_STARTTIME1               1211
#define IDC_BTN_REMOTE1                 1211
#define IDC_ED_JUSTPEAKRATE             1211
#define IDC_ED_STARTLVL_SET             1212
#define IDC_BTN_LOCAL                   1212
#define IDC_ED_DEADTIME1                1212
#define IDC_BTN_LOCAL1                  1212
#define IDC_BTN_CREATE                  1212
#define IDC_ED_STARTLVL_MON             1213
#define IDC_ED_JUSTTIME1                1213
#define IDC_BTN_REMOTE2                 1213
#define IDC_ED_JUSTPEAKSEL              1213
#define IDC_BMP_JUST                    1214
#define IDC_ED_ENDTIME1                 1214
#define IDC_BTN_LOCAL2                  1214
#define IDC_ED_DIFF_GAIN                1214
#define IDC_ED_JUSTLVL_SET              1215
#define IDC_ED_OVERETCHTIME1            1215
#define IDC_BTN_REMOTE3                 1215
#define IDC_ED_JUST_BOX_RATE            1215
#define IDC_ED_JUSTLVL_MON              1216
#define IDC_ED_STARTLEVEL1              1216
#define IDC_BTN_LOCAL3                  1216
#define IDC_ED_JUST_BOX_SEL             1216
#define IDC_ED_JUSTDIFF_SET             1217
#define IDC_ED_JUSTLEVEL1               1217
#define IDC_BTN_REMOTE4                 1217
#define IDC_ED_END_DIFF_SEL             1217
#define IDC_ED_JUSTDIFF_MON             1218
#define IDC_ED_PEAKLEVEL1               1218
#define IDC_BTN_LOCAL4                  1218
#define IDC_ED_END_DIFF_RATE            1218
#define IDC_BMP_JUST2                   1219
#define IDC_ED_ENDLEVEL1                1219
#define IDC_BMP_END                     1219
#define IDC_BTN_REMOTE5                 1219
#define IDC_ED_END_DIFF2_SEL            1219
#define IDC_ED_ENDLVL_SET               1220
#define IDC_ED_STARTTIME2               1220
#define IDC_BTN_LOCAL5                  1220
#define IDC_ED_END_DIFF2_RATE           1220
#define IDC_ED_ENDLVL_MON               1221
#define IDC_ED_DEADTIME3                1221
#define IDC_ED_END_FLAT2                1221
#define IDC_ED_ENDDIFF_J_SET            1222
#define IDC_ED_JUSTTIME2                1222
#define IDC_ED_END_FLAT_RATE            1222
#define IDC_ED_ENDDIFF_J_MON            1223
#define IDC_ED_ENDTIME2                 1223
#define IDC_ED_DIFF_GAIN2               1223
#define IDC_ED_SAMPLING_TM              1223
#define IDC_ED_ENDDIFF_P_SET            1224
#define IDC_ED_OVERETCHTIME2            1224
#define IDC_RDO_START_GAIN_TIME         1224
#define IDC_ED_ENDDIFF_P_MON            1225
#define IDC_ED_STARTLEVEL2              1225
#define IDC_RDO_START_GAIN_PEAK         1225
#define IDC_BMP_JUST3                   1226
#define IDC_ED_JUSTLEVEL2               1226
#define IDC_BMP_OVETCH                  1226
#define IDC_ED_OVERETCH_SET             1227
#define IDC_ED_PEAKLEVEL2               1227
#define IDC_ED_OVERETCH_MON             1228
#define IDC_ED_ENDLEVEL2                1228
#define IDC_ED_ENDTIME_LIMIT            1229
#define IDC_ED_STARTTIME3               1229
#define IDC_ED_JUSTTIME_LIMIT           1230
#define IDC_ED_DEADTIME4                1230
#define IDC_ED_PEAKDATA                 1231
#define IDC_ED_JUSTTIME3                1231
#define IDC_ED_JUSTTIME                 1232
#define IDC_ED_ENDTIME3                 1232
#define IDC_GRAPH_RECT                  1233
#define IDC_ED_OVERETCHTIME3            1234
#define IDC_ED_HALF_TM                  1234
#define IDC_ED_JUST_BOX_WAVE            1234
#define IDC_ED_DIFF_MAX                 1234
#define IDC_CHK_RAWDATA                 1235
#define IDC_ED_STARTLEVEL3              1235
#define IDC_ED_STARTLVL_WAVE            1235
#define IDC_ED_DIFF_MIN                 1235
#define IDC_CHK_RAWDATA_SAVE            1236
#define IDC_TREE_LOG                    1236
#define IDC_ED_DIFF_MIN2                1236
#define IDC_ED_DIFF_MID                 1236
#define IDC_ED_DIFF_MAX2                1236
#define IDC_ED_JUSTLEVEL3               1237
#define IDC_CHK_ROWDATA                 1238
#define IDC_ED_PEAKLEVEL3               1239
#define IDC_ED_ENDLEVEL3                1240
#define IDC_ED_STARTTIME4               1241
#define IDC_ED_STARTTIME5               1242
#define IDC_ED_JUSTTIME4                1243
#define IDC_ED_ENDTIME4                 1244
#define IDC_ED_OVERETCHTIME4            1245
#define IDC_ED_STARTLEVEL4              1246
#define IDC_ED_JUSTLEVEL4               1247
#define IDC_ED_PEAKLEVEL4               1248
#define IDC_ED_ENDLEVEL4                1249
#define IDC_BTN_RCP1                    1250
#define IDC_BTN_RCP2                    1251
#define IDC_ED_STEPNO                   1251
#define IDC_BTN_RCP3                    1252
#define IDC_BTN_RCP4                    1253
#define IDC_ED_TOTAL_TM                 1253
#define IDC_ED_DEADTIME5                1254
#define IDC_BTN_RCP6                    1254
#define IDC_BTN_CLR1                    1254
#define IDC_ED_JUSTTIME5                1255
#define IDC_BTN_CLR2                    1255
#define IDC_BTN_PC1                     1255
#define IDC_ED_ENDTIME5                 1256
#define IDC_BTN_CLR3                    1256
#define IDC_BTN_PC2                     1256
#define IDC_ED_LOTID                    1256
#define IDC_ED_OVERETCHTIME5            1257
#define IDC_BTN_CLR4                    1257
#define IDC_BTN_PC3                     1257
#define IDC_ED_CSTID                    1257
#define IDC_BUTTON1                     1257
#define IDC_BTN_CSV                     1257
#define IDC_BTN_rcpedt                  1257
#define IDC_ED_STARTLEVEL5              1258
#define IDC_BTN_CLR5                    1258
#define IDC_BTN_PC4                     1258
#define IDC_ED_GLSID                    1258
#define IDC_ED_INTEGTIME                1258
#define IDC_BTN_DRAWWAVE                1258
#define IDC_ED_JUSTLEVEL5               1259
#define IDC_BTN_PC5                     1259
#define IDC_ED_GLSID2                   1259
#define IDC_ED_SLOTNO                   1259
#define IDC_BTN_WAVECFGEDT              1259
#define IDC_ED_PEAKLEVEL5               1260
#define IDC_BTN_GRAPHSEL                1260
#define IDC_ED_START_LEVEL              1260
#define IDC_BTN_PC6                     1260
#define IDC_BTN_VIEWSORT                1260
#define IDC_ED_ENDLEVEL5                1261
#define IDC_ED_END_LEVEL                1261
#define IDC_ED_MODE1                    1261
#define IDC_BTN_RCP5                    1262
#define IDC_ED_PEAK_LEVEL               1262
#define IDC_ED_MODE2                    1262
#define IDC_ED_MIN_LEVEL                1263
#define IDC_ED_LOG_LOTID                1263
#define IDC_ED_MODE3                    1263
#define IDC_CHK_DETAIL                  1263
#define IDC_BTN_ALLSEL                  1263
#define IDC_ED_DIFF_LEVEL               1264
#define IDC_ED_LOG_CSTID                1264
#define IDC_ED_MODE4                    1264
#define IDC_BTN_SELECT                  1264
#define IDC_ED_START_TIME               1265
#define IDC_ED_LOG_GLSID                1265
#define IDC_ED_MODE5                    1265
#define IDC_BTN_ALLUNSEL                1265
#define IDC_ED_END_TIME                 1266
#define IDC_ED_LOG_SLOTNO               1266
#define IDC_BTN_UNSELECT                1266
#define IDC_ED_PEAK_TIME                1267
#define IDC_LIST_LOG                    1267
#define IDC_ED_MIN_TIME                 1268
#define IDC_RADIO_PC1                   1269
#define IDC_CHECK1                      1270
#define IDC_CHECK_OVERWRITE             1270
#define IDC_CHK_DIFFOPT                 1270
#define IDC_RADIO_PC2                   1271
#define IDC_ED_GAIN2                    1271
#define IDC_RD_PC1                      1271
#define IDC_RADIO_PC3                   1272
#define IDC_RD_PC2                      1272
#define IDC_RD_PC3                      1273
#define IDC_RADIO_PC4                   1273
#define IDC_RD_PC4                      1274
#define IDC_RADIO_PC5                   1274
#define IDC_ED_WAVE_MIN                 1274
#define IDC_RD_PC5                      1275
#define IDC_ED_WAVE_MAX                 1275
#define IDC_ED_KEY_IP4                  1276
#define IDC_ED_KEY_IP8                  1277
#define IDC_CMB_WAVE_A                  1277
#define IDC_ED_WAVE_A_OFFGAIN1          1278
#define IDC_ED_WAVE_A_OFFGAIN2          1279
#define IDC_ED_WAVE_A_RECIPROCAL        1280
#define IDC_CMB_WAVE_B1                 1281
#define IDC_ED_WAVE_A                   1281
#define IDC_ED_WAVE_B1_OFFGAIN1         1282
#define IDC_ED_WAVE_B1_OFFGAIN2         1283
#define IDC_ED_ADDCNT1                  1284
#define IDC_ED_WAVE_B1                  1284
#define IDC_ED_ADDCNT2                  1285
#define IDC_ED_WAVE_B2                  1285
#define IDC_ED_DIFFCALCVAL              1286
#define IDC_EDI_DIFF_AVERAGE            1287
#define IDC_ED_DIFF_AVE_REPEAT          1288
#define IDC_ED_WAVE_B1_RECIPROCAL       1289
#define IDC_CMB_WAVE_B2                 1290
#define IDC_ED_WAVE_B2_OFFGAIN1         1291
#define IDC_ED_WAVE_B2_OFFGAIN2         1292
#define IDC_ED_WAVE_B2_RECIPROCAL       1293
#define IDC_ED_WAVE_STEP2_AVECNT        1294
#define IDC_ED_WAVE_STEP3_RECIPROCAL    1295
#define IDC_ED_WAVE_STEP3_OFFSET_TYPE   1296
#define IDC_ED_WAVE_STEP3_OFFSET_VAL    1297
#define IDC_ED_WAVE_STEP3_MAXLVL_TYPE   1298
#define IDC_ED_WAVE_STEP3_MAXLVL_VAL    1299
#define IDC_ED_WAVE_STEP3_AVECNT        1300
#define IDC_ED_STEP4_DIFF1              1301
#define IDC_ED_STEP4_DIFF1_RPTAVE       1302
#define IDC_ED_STEP4_DIFF2              1303
#define IDC_ED_STEP4_DIFF2_RPTAVE       1304
#define IDC_ED_WAVE_STEP4_AVECNT        1305
#define IDC_ED_WAVE_STEP4_CORRECT       1306
#define IDC_ED_WAVE_STEP4_CORR_VAL      1307
#define IDC_ED_DISP_DIFF_SCALE          1308
#define IDC_ED_DISP_DIFF_MAX            1309
#define IDC_ED_DISP_DIFF_MAX2           1310
#define IDC_ED_DISP_DIFF_EXP            1310
#define IDC_BTN_DELETE                  1458
#define IDC_ED_PCNO                     1503
#define IDC_ED_PCNETWORK                1504
#define IDC_ED_PCNODE                   1505
#define IDC_ED_PLC_MACHINE              1506
#define IDC_ED_PLC_NETWORK              1507
#define IDC_ED_PLC_NODE                 1508
#define IDC_ED_PORTNO                   1509
#define IDC_ED_IP1                      1510
#define IDC_ED_IP2                      1511
#define IDC_ED_IP3                      1512
#define IDC_ED_IP4                      1513
#define IDC_ED_OMRON_ENABLE             1514
#define IDC_ED_KEY_PORTNO               1515
#define IDC_ED_KEY_IP1                  1516
#define IDC_ED_KEY_IP2                  1517
#define IDC_ED_KEY_IP3                  1518
#define IDC_ED_KEYENCE_ENABLE           1520
#define IDC_BTN_MAX                     1584
#define IDC_BTN_MIN                     1585
#define IDC_BTN_UP                      1586
#define IDC_BTN_DOWN                    1587
#define IDC_ED_USERID                   1592
#define IDC_ED_AUTOLOGOFF               1593
#define IDC_USELIST                     1615
#define IDC_ED_PASSWORD                 1618
#define IDC_ED_CONFIRM                  1619
#define IDC_CMB_LEVEL                   1620
#define IDC_BTN_Q                       1803
#define IDC_BTN_A                       1804
#define IDC_BTN_Z                       1805
#define IDC_BTN_W                       1806
#define IDC_BTN_S                       1807
#define IDC_BTN_X                       1808
#define IDC_BTN_E                       1809
#define IDC_BTN_D                       1810
#define IDC_BTN_C                       1811
#define IDC_BTN_R                       1812
#define IDC_BTN_F                       1813
#define IDC_BTN_V                       1814
#define IDC_BTN_T                       1815
#define IDC_BTN_G                       1816
#define IDC_BTN_B                       1817
#define IDC_BTN_Y                       1818
#define IDC_BTN_H                       1819
#define IDC_BTN_N                       1820
#define IDC_BTN_U                       1821
#define IDC_BTN_J                       1822
#define IDC_BTN_M                       1823
#define IDC_BTN_I                       1824
#define IDC_BTN_K                       1825
#define IDC_BTN_O                       1826
#define IDC_BTN_L                       1827
#define IDC_BTN_P                       1828
#define IDC_BTN_SEMICOLON               1829
#define IDC_BTN_COLON2                  1830
#define IDC_BTN_CANMA                   1831
#define IDC_BTN_DOT                     1832
#define IDC_BTN_QUESTION                1833
#define IDC_BTN_BKSP                    1834

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        433
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1282
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
